// Unified Campus OS Data Store with Domain Collections, Indexes & Spatial Graphs

export class CampusDataStore {
  constructor() {
    this.users = [
      {
        id: 'usr_manoj_1',
        name: 'Manoj Reddy',
        email: 'dullamanojreddy@gmail.com',
        role: 'STUDENT',
        studentId: '21B81A0589',
        department: 'Information Technology',
        year: '3rd Year',
        semester: 'VI',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        campusPoints: 1250,
        phone: '+91 98765 43210',
        activeRfid: 'RFID-9842-IT-21',
      },
      {
        id: 'usr_faculty_1',
        name: 'Prof. Ananya Roy',
        email: 'ananya.roy@campus.edu',
        role: 'FACULTY',
        department: 'Computer Science',
        avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        campusPoints: 2400,
      },
      {
        id: 'usr_vendor_1',
        name: 'Suresh Canteen Manager',
        email: 'canteen_a@campus.edu',
        role: 'VENDOR',
        vendorId: 'canteen_a',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        campusPoints: 800,
      },
      {
        id: 'usr_maint_1',
        name: 'Rajesh Maintenance Lead',
        email: 'maint@campus.edu',
        role: 'MAINTENANCE',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        campusPoints: 950,
      },
      {
        id: 'usr_admin_1',
        name: 'Dr. K. V. Sharma (Dean)',
        email: 'dean.admin@campus.edu',
        role: 'ADMIN',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
        campusPoints: 5000,
      },
    ];

    this.currentUser = this.users[0];

    this.buildings = [
      {
        id: 'cse',
        name: 'CSE Block (Computer Science)',
        code: 'CSE',
        category: 'ACADEMIC',
        floorCount: 4,
        description: 'Department of Computer Science & Engineering, AI Labs, and Project Centers.',
        facilities: ['High-speed Wi-Fi', 'Smart Projectors', 'Air Conditioning', 'Elevator', 'Restrooms'],
        coordinates: { x: 35, y: 40 },
        entryNodeId: 'node_cse_entry',
      },
      {
        id: 'it',
        name: 'IT Block (Information Tech)',
        code: 'IT',
        category: 'ACADEMIC',
        floorCount: 4,
        description: 'Department of Information Technology, Cloud Computing Lab, and Software Engineering Studios.',
        facilities: ['Wi-Fi', 'Research Labs', 'Seminar Rooms'],
        coordinates: { x: 50, y: 35 },
        entryNodeId: 'node_it_entry',
      },
      {
        id: 'admin',
        name: 'Admin Block',
        code: 'ADM',
        category: 'ADMINISTRATIVE',
        floorCount: 3,
        description: 'Principal Office, Dean Academics, Admissions, and Examination Cell.',
        facilities: ['Helpdesk', 'Fee Counter', 'Meeting Chambers'],
        coordinates: { x: 20, y: 25 },
        entryNodeId: 'node_adm_entry',
      },
      {
        id: 'library',
        name: 'Central Library',
        code: 'LIB',
        category: 'LIBRARY',
        floorCount: 3,
        description: 'Over 50,000 volumes, IEEE digital access library, quiet reading halls.',
        facilities: ['Digital Lounge', 'Discussion Cubicles', 'Printing Center'],
        coordinates: { x: 60, y: 20 },
        entryNodeId: 'node_lib_entry',
      },
      {
        id: 'canteen_a',
        name: 'Canteen A (Food Court)',
        code: 'FC1',
        category: 'FOOD',
        floorCount: 1,
        description: 'Main campus food court with express pickup counters and multi-cuisine meals.',
        facilities: ['Express Counter', 'UPI & Student ID Pay', 'Outdoor Seating'],
        coordinates: { x: 25, y: 70 },
        entryNodeId: 'node_fc1_entry',
      },
      {
        id: 'canteen_b',
        name: 'Canteen B (Quick Bites)',
        code: 'FC2',
        category: 'FOOD',
        floorCount: 1,
        description: 'Fast food, hot snacks, fresh juices, and south-Indian breakfast items.',
        facilities: ['Beverage Bar', 'Snack Counter'],
        coordinates: { x: 45, y: 75 },
        entryNodeId: 'node_fc2_entry',
      },
      {
        id: 'seminar',
        name: 'Main Seminar Hall',
        code: 'SH1',
        category: 'AUDITORIUM',
        floorCount: 2,
        description: '500-seat auditorium with Dolby audio, stage lighting, and projection systems.',
        facilities: ['Acoustic Paneling', 'Live Broadcast System', 'Podium'],
        coordinates: { x: 70, y: 55 },
        entryNodeId: 'node_sh1_entry',
      },
      {
        id: 'sports',
        name: 'Sports Complex',
        code: 'SPT',
        category: 'SPORTS',
        floorCount: 2,
        description: 'Indoor badminton courts, gymnasium, table tennis, and sports equipment store.',
        facilities: ['Locker Rooms', 'Gym Equipment', 'First Aid Station'],
        coordinates: { x: 80, y: 80 },
        entryNodeId: 'node_spt_entry',
      },
    ];

    this.rooms = [
      { id: 'r-302', buildingId: 'cse', roomNumber: '302', name: 'Database Management Systems Lab', type: 'LAB', floorNumber: 3, capacity: 60, nodeId: 'node_cse_r302' },
      { id: 'r-304', buildingId: 'cse', roomNumber: '304', name: 'Computer Networks Lab', type: 'LAB', floorNumber: 3, capacity: 60, nodeId: 'node_cse_r304' },
      { id: 'r-306', buildingId: 'cse', roomNumber: '306', name: 'Software Engineering Classroom', type: 'CLASSROOM', floorNumber: 3, capacity: 70, nodeId: 'node_cse_r306' },
      { id: 'r-308', buildingId: 'cse', roomNumber: '308', name: 'Web Technologies Studio', type: 'CLASSROOM', floorNumber: 3, capacity: 70, nodeId: 'node_cse_r308' },
      { id: 'r-ai1', buildingId: 'cse', roomNumber: 'AI Lab - 1', name: 'Artificial Intelligence & Robotics Lab', type: 'LAB', floorNumber: 1, capacity: 50, nodeId: 'node_cse_ai1' },
      { id: 'r-201', buildingId: 'cse', roomNumber: '201', name: 'Coding Club Activity Hall', type: 'CLASSROOM', floorNumber: 2, capacity: 80, nodeId: 'node_cse_r201' },
      { id: 'r-it201', buildingId: 'it', roomNumber: 'IT-201', name: 'Cloud Computing Lab', type: 'LAB', floorNumber: 2, capacity: 65, nodeId: 'node_it_r201' },
      { id: 'r-lib101', buildingId: 'library', roomNumber: 'LIB-101', name: 'Digital Periodical Hall', type: 'LIBRARY', floorNumber: 1, capacity: 120, nodeId: 'node_lib_r101' },
    ];

    // Spatial Map Waypoint Graph for Campus Routing (Dijkstra)
    this.mapNodes = [
      { id: 'node_main_gate', name: 'Main Campus Gate', x: 10, y: 50 },
      { id: 'node_plaza', name: 'Central Fountain Plaza', x: 40, y: 50 },
      { id: 'node_cse_entry', name: 'CSE Block Entrance', x: 35, y: 40 },
      { id: 'node_cse_r304', name: 'CSE Room 304 (3rd Floor)', x: 35, y: 38 },
      { id: 'node_cse_r302', name: 'CSE Room 302 (3rd Floor)', x: 35, y: 42 },
      { id: 'node_cse_ai1', name: 'CSE AI Lab - 1 (Ground Floor)', x: 34, y: 40 },
      { id: 'node_it_entry', name: 'IT Block Entrance', x: 50, y: 35 },
      { id: 'node_adm_entry', name: 'Admin Entrance', x: 20, y: 25 },
      { id: 'node_lib_entry', name: 'Library Entrance', x: 60, y: 20 },
      { id: 'node_fc1_entry', name: 'Canteen A Entrance', x: 25, y: 70 },
      { id: 'node_fc2_entry', name: 'Canteen B Entrance', x: 45, y: 75 },
      { id: 'node_sh1_entry', name: 'Seminar Hall Entrance', x: 70, y: 55 },
      { id: 'node_spt_entry', name: 'Sports Complex Entrance', x: 80, y: 80 },
    ];

    this.mapEdges = [
      { from: 'node_main_gate', to: 'node_adm_entry', weight: 45 },
      { from: 'node_main_gate', to: 'node_plaza', weight: 60 },
      { from: 'node_plaza', to: 'node_cse_entry', weight: 35 },
      { from: 'node_plaza', to: 'node_it_entry', weight: 40 },
      { from: 'node_plaza', to: 'node_fc1_entry', weight: 50 },
      { from: 'node_plaza', to: 'node_fc2_entry', weight: 55 },
      { from: 'node_plaza', to: 'node_sh1_entry', weight: 70 },
      { from: 'node_cse_entry', to: 'node_cse_r304', weight: 25 },
      { from: 'node_cse_entry', to: 'node_cse_r302', weight: 20 },
      { from: 'node_cse_entry', to: 'node_cse_ai1', weight: 10 },
      { from: 'node_it_entry', to: 'node_lib_entry', weight: 45 },
      { from: 'node_sh1_entry', to: 'node_spt_entry', weight: 50 },
    ];

    this.schedule = [
      {
        id: 'sched-1',
        time: '09:00 AM',
        subject: 'DBMS',
        code: 'CS301',
        room: 'CSE Block - 302',
        roomNumber: '302',
        buildingId: 'cse',
        faculty: 'Dr. S. K. Sharma',
        color: '#3b82f6',
        status: 'completed',
        day: 'Monday',
      },
      {
        id: 'sched-2',
        time: '10:00 AM',
        subject: 'Computer Networks',
        code: 'CS302',
        room: 'CSE Block - 304',
        roomNumber: '304',
        buildingId: 'cse',
        faculty: 'Prof. Ananya Roy',
        color: '#10b981',
        status: 'ongoing',
        day: 'Monday',
      },
      {
        id: 'sched-3',
        time: '11:00 AM',
        subject: 'AI Lab',
        code: 'CS303L',
        room: 'AI Lab - 1',
        roomNumber: 'AI Lab - 1',
        buildingId: 'cse',
        faculty: 'Dr. Vikramaditya',
        color: '#84cc16',
        status: 'upcoming',
        day: 'Monday',
      },
      {
        id: 'sched-4',
        time: '02:00 PM',
        subject: 'Software Engineering',
        code: 'CS304',
        room: 'CSE Block - 306',
        roomNumber: '306',
        buildingId: 'cse',
        faculty: 'Prof. Ramesh K.',
        color: '#a855f7',
        status: 'upcoming',
        day: 'Monday',
      },
      {
        id: 'sched-5',
        time: '03:00 PM',
        subject: 'Web Technologies',
        code: 'CS305',
        room: 'CSE Block - 308',
        roomNumber: '308',
        buildingId: 'cse',
        faculty: 'Dr. Priya Desai',
        color: '#f97316',
        status: 'upcoming',
        day: 'Monday',
      },
    ];

    this.vendors = [
      {
        id: 'canteen_a',
        name: 'Canteen A (Food Court)',
        location: 'Ground Floor, Food Court Block',
        openingHours: '08:00 AM - 08:30 PM',
        status: 'OPEN',
        crowdLevel: 'Moderate',
        averageWaitMinutes: 10,
        rating: 4.6,
      },
      {
        id: 'canteen_b',
        name: 'Canteen B (Quick Bites)',
        location: 'Central Lawn Pathway',
        openingHours: '08:30 AM - 07:00 PM',
        status: 'OPEN',
        crowdLevel: 'Low',
        averageWaitMinutes: 5,
        rating: 4.8,
      },
    ];

    this.foodItems = [
      {
        id: 'food-1',
        vendorId: 'canteen_a',
        name: 'Paneer Biryani',
        price: 140,
        category: 'Main Course',
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=300&auto=format&fit=crop&q=80',
        isAvailable: true,
        preparationTimeMinutes: 12,
        dietary: 'VEG',
      },
      {
        id: 'food-2',
        vendorId: 'canteen_b',
        name: 'Veg Thali (Special)',
        price: 90,
        category: 'Meals',
        image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=300&auto=format&fit=crop&q=80',
        isAvailable: true,
        preparationTimeMinutes: 8,
        dietary: 'VEG',
      },
      {
        id: 'food-3',
        vendorId: 'canteen_a',
        name: 'Masala Dosa',
        price: 60,
        category: 'Breakfast',
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=300&auto=format&fit=crop&q=80',
        isAvailable: true,
        preparationTimeMinutes: 6,
        dietary: 'VEG',
      },
      {
        id: 'food-4',
        vendorId: 'canteen_a',
        name: 'Crispy Samosa (2 pcs)',
        price: 30,
        category: 'Snacks',
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300&auto=format&fit=crop&q=80',
        isAvailable: true,
        preparationTimeMinutes: 3,
        dietary: 'VEG',
      },
      {
        id: 'food-5',
        vendorId: 'canteen_b',
        name: 'Cold Coffee with Ice Cream',
        price: 50,
        category: 'Beverages',
        image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=300&auto=format&fit=crop&q=80',
        isAvailable: true,
        preparationTimeMinutes: 4,
        dietary: 'VEG',
      },
      {
        id: 'food-6',
        vendorId: 'canteen_a',
        name: 'Veg Fried Rice with Manchurian',
        price: 120,
        category: 'Chinese',
        image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=300&auto=format&fit=crop&q=80',
        isAvailable: true,
        preparationTimeMinutes: 10,
        dietary: 'VEG',
      },
    ];

    this.orders = [
      {
        id: 'ord_1234',
        orderNumber: '1234',
        userId: 'usr_manoj_1',
        vendorId: 'canteen_a',
        vendorName: 'Canteen A',
        items: [
          {
            foodItemId: 'food-1',
            name: 'Paneer Biryani',
            price: 140,
            quantity: 1,
          },
        ],
        subtotal: 140,
        tax: 0,
        total: 140,
        status: 'PREPARING',
        pickupTime: '12:45 PM',
        pickupCounter: 'Counter 2',
        qrToken: 'QR-ORD-1234-VALID',
        createdAt: new Date(Date.now() - 600000).toISOString(),
        updatedAt: new Date(Date.now() - 300000).toISOString(),
      },
    ];

    this.notices = [
      {
        id: 'not-1',
        title: 'Placement Drive by TCS',
        subtitle: 'Eligible for 2026 Batch CSE/IT',
        timeAgo: '2h ago',
        category: 'PLACEMENT',
        priority: 'URGENT',
        badgeText: 'NEW',
        badgeType: 'new',
        icon: 'megaphone',
        publishedAt: new Date(Date.now() - 7200000).toISOString(),
        isPublished: true,
        author: 'Placement Cell',
      },
      {
        id: 'not-2',
        title: 'Independence Day Celebration',
        subtitle: 'Flag hoisting at 8:30 AM in Main Ground',
        timeAgo: '1d ago',
        category: 'EVENT',
        priority: 'IMPORTANT',
        badgeText: 'IMPORTANT',
        badgeType: 'important',
        icon: 'info',
        publishedAt: new Date(Date.now() - 86400000).toISOString(),
        isPublished: true,
        author: 'Cultural Committee',
      },
      {
        id: 'not-3',
        title: 'Mid Sem Exams Timetable',
        subtitle: 'Schedule released for all branches',
        timeAgo: '2d ago',
        category: 'ACADEMIC',
        priority: 'NORMAL',
        badgeText: 'ACADEMIC',
        badgeType: 'academic',
        icon: 'book',
        publishedAt: new Date(Date.now() - 172800000).toISOString(),
        isPublished: true,
        author: 'Examination Branch',
      },
    ];

    this.events = [
      {
        id: 'evt-1',
        title: 'Hackathon 2025',
        subtitle: 'Smart India Hackathon Internal Round',
        month: 'AUG',
        day: '19',
        location: 'Seminar Hall',
        time: '10:00 AM',
        category: 'Hackathon',
        capacity: 300,
        registeredCount: 287,
        registeredUserIds: ['usr_manoj_1'],
        isPublished: true,
      },
      {
        id: 'evt-2',
        title: 'Coding Club Meetup',
        subtitle: 'DSA Session for Beginners',
        month: 'AUG',
        day: '21',
        location: 'CSE Block - 201',
        time: '04:00 PM',
        category: 'Club',
        capacity: 100,
        registeredCount: 78,
        registeredUserIds: [],
        isPublished: true,
      },
      {
        id: 'evt-3',
        title: 'Workshop on AI/ML',
        subtitle: 'Hands-on Session with PyTorch',
        month: 'AUG',
        day: '25',
        location: 'AI Lab - 1',
        time: '11:00 AM',
        category: 'Workshop',
        capacity: 60,
        registeredCount: 52,
        registeredUserIds: [],
        isPublished: true,
      },
    ];

    this.complaints = [
      {
        id: 'c-1',
        ticketNumber: 'TKT-9842',
        userId: 'usr_manoj_1',
        userName: 'Manoj Reddy',
        category: 'Classroom Projector / AC',
        location: 'CSE Block - Room 304',
        roomId: 'r-304',
        buildingId: 'cse',
        description: 'Projector display flickering intermittently during morning lectures.',
        priority: 'HIGH',
        status: 'IN_PROGRESS',
        assignedTo: 'Maintenance Team A (Electrical)',
        createdAt: new Date(Date.now() - 3600000).toISOString(),
        timeline: [
          { status: 'Submitted', timestamp: '09:15 AM', note: 'Ticket logged by Manoj Reddy' },
          { status: 'Assigned', timestamp: '09:30 AM', note: 'Assigned to Tech Senior Suresh' },
          { status: 'In Progress', timestamp: '10:00 AM', note: 'Technician inspecting HDMI & lamp ballast' },
        ],
      },
    ];

    this.bookings = [
      { id: 'b-1', name: 'Main Seminar Hall A', type: 'AUDITORIUM', capacity: 300, location: 'Seminar Hall Building', isAvailable: true },
      { id: 'b-2', name: 'IoT Research Lab', type: 'LAB', capacity: 40, location: 'IT Block - 2nd Floor', isAvailable: true },
      { id: 'b-3', name: 'Badminton Court 1', type: 'SPORTS', capacity: 4, location: 'Sports Complex', isAvailable: true },
      { id: 'b-4', name: 'CSE Project Innovation Room', type: 'LAB', capacity: 25, location: 'CSE Block - 3rd Floor', isAvailable: true },
    ];

    this.bookingReservations = [
      {
        id: 'res-1',
        resourceId: 'b-1',
        resourceName: 'Main Seminar Hall A',
        userId: 'usr_faculty_1',
        date: '2026-08-20',
        startTime: '10:00',
        endTime: '12:00',
        purpose: 'Department Induction Program',
        status: 'CONFIRMED',
      },
    ];

    this.notifications = [
      {
        id: 'notif-1',
        userId: 'usr_manoj_1',
        title: 'Order Preparing',
        message: 'Your Paneer Biryani is currently being prepared at Canteen A Counter 2.',
        type: 'ORDER_STATUS_CHANGED',
        read: false,
        createdAt: new Date(Date.now() - 300000).toISOString(),
      },
      {
        id: 'notif-2',
        userId: 'usr_manoj_1',
        title: 'Class Countdown',
        message: 'Computer Networks lecture in Room 304 starts in 15 minutes.',
        type: 'SCHEDULE_ALERT',
        read: true,
        createdAt: new Date(Date.now() - 3600000).toISOString(),
      },
    ];

    this.feedbacks = [
      { id: 'fb-1', userId: 'usr_manoj_1', rating: 5, comment: 'Canteen food pickup was fast and hot!', createdAt: new Date().toISOString() },
    ];

    // Pending AI Actions store (e.g. for write operations awaiting user confirmation)
    this.pendingAIActions = new Map();
  }
}

export const dataStore = new CampusDataStore();
